name: Run OddEven Script
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Match your script's version
          
      - name: Install dependencies
        run: pip install requests  # Add other packages if needed
        
      - name: Run script
        run: python cloudbet/oddeven.py
